_wandb:
    value:
        cli_version: 0.22.3
        e:
            qvbdf43z7bavos8px56io6anu1hxmb9x:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "501809635328"
                        used: "378898259968"
                email: bierling.lukas@gmail.com
                executable: /home/lukas/anaconda3/envs/traize-backend/bin/python
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-200adeea-6243-073d-9791-35be73ba1243
                host: lukas-ThinkStation-P920
                memory:
                    total: "134678298624"
                os: Linux-6.14.0-34-generic-x86_64-with-glibc2.39
                program: /home/lukas/Projects/ir2/joint-reinforcing/partition-classifier/train.py
                python: CPython 3.10.0
                root: /home/lukas/Projects/ir2/joint-reinforcing/partition-classifier
                startedAt: "2025-11-04T15:22:09.021832Z"
                writerId: qvbdf43z7bavos8px56io6anu1hxmb9x
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 100
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 100
                - 105
            "3":
                - 13
                - 16
            "4": 3.10.0
            "5": 0.22.3
            "6": 4.56.1
            "12": 0.22.3
            "13": linux-x86_64
